### ISSUE TITLE
Get singularity working on CCLyon

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/starterkit#5]
We just need to make sure we can write to a directory OK. I think we are pretty close with this one. Can everyone run from my singularity install? Should we have an official central one? If so, where should it be on the disk?

**Comment by drbenmorgan** [comment]
I think we start by getting people to `singularity pull` as they'll need this if running outside Lyon.

CCLyon docs mention that they provide a CVMFS service to host custom Singularity images. We (read me probably) should set that up for the medium/long term, but no guarantees on it being ready for Annecy.

**Comment by drbenmorgan** [comment]
I'd now say this is fixed, as the current images support graphics, and the instructions on SuperNEMO-DBD/brew show how the relevant directories on CC-IN2P3 can be bound, and how to get X11 forwarding working.
